### ISSUE TITLE
Redwise Author is 'api.zotero.org' instead of actual document author

### ISSUE THREAD

**Issue by Stvad** [e-alizadeh/Zotero2Readwise#22]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/81347/164868944-9047c86d-b9fb-4cb9-ad57-afbf1817e38d.png">

**Comment by e-alizadeh** [comment]
Hi @Stvad.

- May I ask when have you started using Zotero2Readwise library?
I've noticed this before and pushed a fix in [this PR](https://github.com/e-alizadeh/Zotero2Readwise/pull/14). However, your issue might be different. 

Another question, does Zotero has an author for that particular document?

**Comment by Stvad** [comment]
Hey @e-alizadeh probably ~10 minutes before posting this issue :). Also I've used the Github Actions workflow and not the library directly.

Ah, you're right, I thought that the document had the appropriate metadata, but it seems the author is actually missing. It'd be helpful i this case to set a more explicit "missing" label if that's the reason for this!

**Comment by e-alizadeh** [comment]
@Stvad. While this is not related to your issue. Please install a version I just released few minutes ago (0.2.4)! Basically, I'm not expecting to see api.zotero.org and I forgot to release a bugfix I had resolved on January! 🤦

Once you install the new version, could you please check if that happens again or not? Since multiple apps can be integrated to Readwise, I thought showing the source might actually help if no author is provided.

**Comment by Stvad** [comment]
Ah, you already do that, though the link is to the item vs specific highlight

**Comment by noeleont** [comment]
@Stvad since #17 we actually link to the specific highlight, can we close this?
